### ISSUE TITLE
[2.0-preview] Demos don't work as expected

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-scroll-header-panel#107]
Most of the demos (transform-header-1.html, transform-header-3.html, transform-header-4.html, keep-header.html, ...) don't seem to work. For example, header bg image is not showing, the icon buttons are missing.

### Expected outcome

All the demos should work and look just like in v1 of paper-scroll-header-panel

### Actual outcome

Most of the demos don't look like those in v1 of paper-scroll-header-panel

### Steps to reproduce

1. Run all the demos

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 10
- [x] Safari 9
- [x] Edge
- [x] IE 11

**Comment by blasten** [comment]
The demos are working again. I changed the default selector to `slot="top"` in paper-toolbar, so that was why the content wasn't showing up. Also, there's a bug in Chrome around using `url(..)` as  a value of a custom property. https://bugs.chromium.org/p/chromium/issues/detail?id=618165
