### ISSUE TITLE
Toolbar title does no longer transforms properly

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-scroll-header-panel#15]
Scroll https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/index.html to see "Title".

@blasten it may have something to do with https://github.com/PolymerElements/paper-toolbar/commit/a2512f2d533132017338fe758c8c97769900d8a9

**Comment by blasten** [comment]
@ebidel actually I sent a PR with the fix: https://github.com/PolymerElements/paper-scroll-header-panel/pull/14

**Comment by blasten** [comment]
![screen shot 2015-06-15 at 2 51 57 pm](https://cloud.githubusercontent.com/assets/1410613/8171611/18b155be-136e-11e5-8a58-d82531cb29fb.png)

Wait, that is weird.

**Comment by blasten** [comment]
I see two titles in Chrome 43... Although it works fine in Chrome Canary as well as firefox and Safari. 

It seems like the `transform` to the title doesn't create a new stacking context or it misses a repaint cycle, but `isolation: isolate;` does force it:  https://github.com/PolymerElements/paper-scroll-header-panel/pull/14/files#diff-9488f05de924be751bb55558e4617b2dR60

**Comment by ebidel** [comment]
@blasten should we do a release with this fix?

**Comment by blasten** [comment]
@ebidel yes!

**Comment by blasten** [comment]
@ebidel I tagged `v1.0.3`!

**Comment by ebidel** [comment]
@blasten turns out this is back if you turn on native SD using `?dom=shadow`

**Comment by blasten** [comment]
@ebidel that's right, `paper-toolbar` has this problem:
https://github.com/PolymerElements/paper-toolbar/issues/26

For the case of scroll-header-panel, you see the correct font-size n shady DOM because I can increase the specificity of the selector used to style `.title`, but that's not the case of Shadow DOM.
