### ISSUE TITLE
Consider using css isolation on .title children

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-scroll-header-panel#17]
`.title` light dom children part of `<paper-toolbar>`, but this element provides the scroll effects. Not sure where this should be filed.

For context, see github.com/PolymerElements/paper-scroll-header-panel/pull/14

**Comment by frankiefu** [comment]
`isolation` is not needed anymore:
https://github.com/PolymerElements/paper-scroll-header-panel/pull/23
