### ISSUE TITLE
middle title

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-scroll-header-panel#25]
From: @chuckh
https://github.com/PolymerElements/polymer-starter-kit/issues/206

I have done some experimenting with `paper-scroll-header-panel`. For migrating from `paper-header-panel` to `paper-scroll-header-panel` I believe we should keep same functionality we have now. So we would use the `keep-condensed-header` on `paper-scroll-header-panel`. Below is example of that. One issue I am running into when using a middle title it is not being condensed correctly.  It uses whatever's in  `<div class="bottom">Bottom Sub title</div>` instead of using title in `<div class="middle title">Middle Title</div>`.

![paper-scroll-header-panel-example](https://cloud.githubusercontent.com/assets/19915/8335346/f32eafea-1a51-11e5-8122-6386a0b8b41c.gif)
### Code excerpt for above example.

```
<paper-scroll-header-panel keep-condensed-header>
    <paper-toolbar class="tall">
      <paper-icon-button icon="arrow-back"></paper-icon-button>
      <div class="flex"></div>
      <paper-icon-button icon="search"></paper-icon-button>
      <paper-icon-button icon="more-vert"></paper-icon-button>
      <div class="middle title">Middle Title</div>
      <div class="bottom">Bottom Sub title</div>
    </paper-toolbar>

    <div class="content">
      <sample-content size="100"></sample-content>
    </div>
  </paper-scroll-header-panel>
```

Gist of entire code for example above.
https://gist.github.com/chuckh/9ec69609ae180c55ec8f

@addyosmani any thoughts?

**Comment by blasten** [comment]
@chuckh you would need to add the `condenses` attribute along with `keep-condensed-header`. 

In the examples, condensed headers seem to only work if the title is at the bottom. That's because scroll-header-panel only zooms in/out the title; in other words, it doesn't translate the title yet. 
I've been playing with some ideas to fix this. I guess we will also need to fade in/out the elements that  aren't a title or the navigation items.

cc @frankiefu for any thoughts.

**Comment by chuckh** [comment]
@blasten any progress on handling a middle title?  

So the above should be `<paper-scroll-header-panel condenses keep-condensed-header>`.

**Comment by frankiefu** [comment]
@chuckh You can add addition code to the custom transformation to make the middle title to move/translate to the bottom while condensing.  Something like this should work:
https://gist.github.com/frankiefu/e42bc14d389e94b86d5a

As @blasten  mentioned we are also working on an enhancement to make the title transformation easier so you don't have to write the code yourself.  It may make sense for starter-kit to wait for the enhancement to land before moving to use `paper-scroll-header-panel`.

**Comment by chuckh** [comment]
@frankiefu I agree starter kit should wait for the enhancement before moving to `paper-scroll-header-panel`.  Also thanks for the work around code example.

**Comment by chuckh** [comment]
@frankiefu I created a demo based your code with the middle and bottom titles area working. I plan to create a pull request for PSK using this method. I slacked with the PSK team and they would like to move forward with the work around for now. Once the `paper-scroll-header-panel` is enhancement we will update PSK with it.

#### This is a gist of the code:

https://gist.github.com/chuckh/9729813fbfe0484da1ca

#### Example of how it works

![paper-scroll-header-panel-titles-transform](https://cloud.githubusercontent.com/assets/19915/8462863/6e3f1d52-1feb-11e5-91ae-8f5b4c1c4de3.gif)

**Comment by blasten** [comment]
@chuckh that looks great, good job! I will work on this as soon as I can.

**Comment by chuckh** [comment]
@blasten have you had a chance to work on this? I have found an issue in PSK with the approach. The middle title is replaced by bottom title when drawer is open or closed. See:

![resize-header-bug](https://cloud.githubusercontent.com/assets/19915/9768202/0233ec32-56d7-11e5-96f7-0a0f25b4e21c.gif)

What I found:
1. It happens when drawer is opened or closed, after paper-responsive-change event is fired
2. It is not a timing issue (using async did help when calling the transforms)

An issue is open for PSK for this problem at https://github.com/PolymerElements/polymer-starter-kit/issues/274

**Comment by blasten** [comment]
@chuckh It's among my top priorities. FYI: @frankiefu and I have been working on new app layout elements: https://github.com/PolymerLabs/app-layout  

We improved a lot the design (both API and how it feels) as well as performance in the new layout elements and although it's still a work in progress, we would like to have a stable release very soon.

I believe this functionality will come along with the new layout elements.

**Comment by chuckh** [comment]
@blasten great! `app-layout` looks sweet, nice work. Hopefully when it is stable we can incorporate into Polymer Starter Kit.

**Comment by chuckh** [comment]
@blasten any progress fixing the 

> middle title is replaced by bottom title when drawer is open or closed.

See https://github.com/PolymerElements/paper-scroll-header-panel/issues/25#issuecomment-138974570. 

This is related to PSK issue PolymerElements/polymer-starter-kit#274.

**Comment by addyosmani** [comment]
After speaking with Taylor, it looks like it might be a few months before we'll be able to switch PSK over to using the `app-layout` collection. 

I realise it totally makes sense to focus our efforts there, but in case there's bandwidth to fix the above issue, we'd totally :heart: it.

**Comment by blasten** [comment]
@addyosmani Yup. check this out: https://github.com/PolymerLabs/app-layout/issues/13

**Comment by blasten** [comment]
@addyosmani @chuckh The latest app-layout is out https://github.com/PolymerLabs/app-layout and I hope you guys find it very useful. I'm closing this issue as we have a new model that allows to build animations like this one.
