### ISSUE TITLE
When this.header is undefined.

### ISSUE THREAD

**Issue by loneleeandroo** [PolymerElements/paper-scroll-header-panel#26]
In certain situations, <code>this.header</code> may be undefined. 

In paper-scroll-header-panel v1.0.4, Lines 381-2 shown here:

```
381   // adjust top bar in paper-header so the top bar stays at the top
382   if (!this.scrollAwayTopbar && this.header.$ && this.header.$.topBar) {
```

could be changed to:

```
381   // adjust top bar in paper-header so the top bar stays at the top
382   if (!this.scrollAwayTopbar && this.header && this.header.$ && this.header.$.topBar) {
```

to accomodate for that.

**Comment by blasten** [comment]
This looks familiar. cc @frankiefu

**Comment by blasten** [comment]
This was fixed in https://github.com/PolymerElements/paper-scroll-header-panel/pull/22, but it wasn't tagged yet.

You can update now to the latest version:  `bower install PolymerElements/paper-scroll-header-panel#^1.0.0`
