### ISSUE TITLE
Header does not condense in a paper-drawer-panel with webcomponentsjs#0.7.6

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-scroll-header-panel#31]
When I use paper-scroll-header-panel in a paper-drawer-panel with webcomponentsjs#0.7.6, header condensation works well on Chrome, but not on Safari and Firefox.

I've created a demo which reproduces this issue.
https://github.com/naoak/paper-scroll-header-panel/commit/864413b5d00c9581b4330e15441265889262d5ed#diff-44621229bee79105bf107156a4af4192

Strangely enough, not in a paper-drawer-panel or with webcomponentsjs#0.7.5, the header condensation works well on any browsers. So I investigated webcomponentsjs#0.7.6 commits, and finally, I've discovered that https://github.com/webcomponents/webcomponentsjs/commit/c8ea79554e14b1aa486610ebbaf2d79f20962091 is closely related with this issue.

**Comment by blasten** [comment]
@naoak this is now fixed!. You should update `bower update`

**Comment by naoak** [comment]
It works perfectly! Thanks:)
