### ISSUE TITLE
Problems with neon-animated-pages and header height

### ISSUE THREAD

**Issue by MeloJR** [PolymerElements/paper-scroll-header-panel#33]
I use the `neon-animated-pages` component to show different pages of my application, and I use the `paper-scroll-header-panel` component in some of these pages . The problem is that the `paper-scroll-header-panel` does not get the correct height of the paper-toolbar, so the toolbar is above the content of my page.
If I invoke the `measureHeaderHeight` explicitly the component get the correct height and it works perfectly so I think it is because the entire page is hidden until I show it (`neon-animated-pages` behavior).

Am I doing something wrong? If not, is there any way to achieve my goal?

Thank you!

**Comment by blasten** [comment]
@MeloJR can you provide a code snippet to see how you are using neon-animated-pages?

**Comment by MeloJR** [comment]
Yes, of course, here it is.

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Test</title>

    <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>

    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="bower_components/neon-animation/neon-animated-pages.html">
    <link rel="import" href="bower_components/neon-animation/neon-animatable.html">
    <link rel="import" href="bower_components/paper-scroll-header-panel/paper-scroll-header-panel.html">
    <link rel="import" href="bower_components/paper-scroll-header-panel/demo/sample-content.html">
    <link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
    <link rel="import" href="bower_components/paper-drawer-panel/paper-drawer-panel.html">
    <link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html">
    <link rel="import" href="bower_components/iron-icons/iron-icons.html">
  </head>
  <body>
    <template id="income" is="dom-bind">
      <neon-animated-pages selected="{{selected}}" class="fit">
        <neon-animatable class="horizontal layout center-center">Page 1</neon-animatable>
        <neon-animatable class="horizontal layout center-center">Page 2</neon-animatable>
        <neon-animatable class="horizontal layout center-center">Page 3</neon-animatable>
        <neon-animatable>
          <paper-scroll-header-panel id="panel" condeses class="fit">
            <paper-toolbar class="tall">
              <paper-icon-button icon="menu"></paper-icon-button>
              <div class="flex"></div>
              <paper-icon-button icon="add"></paper-icon-button>
              <div class="title bottom">Title</div>
            </paper-toolbar>
            <div>
              <sample-content size="100"></sample-content>
            </div>
          </paper-scroll-header-panel>
        </neon-animatable>
      </neon-animated-pages>
    </template>
    <script>
      var temp = document.querySelector("template");
      temp.selected = 0;
      temp.next = function() {
          temp.selected = (temp.selected + 1) % 4; 
      };
    </script>
  </body>
</html>
```

It is a simple test. In my application the things are a bit more complicated but the problem is the same: when we go to page 4 (`temp.selected = 3`) the toolbar is above the content:

![captura de pantalla 2015-07-17 a las 19 56 23](https://cloud.githubusercontent.com/assets/5193005/8753722/4121a526-2cbe-11e5-97ac-a6609105610a.png)

But if we execute `temp.$.panel.measureHeaderHeight()` the problem is solved:

![captura de pantalla 2015-07-17 a las 19 57 41](https://cloud.githubusercontent.com/assets/5193005/8753740/57e4c0ae-2cbe-11e5-9f16-a96d397cb907.png)

I don't know if I am doing something wrong. Is it my fault? `paper-scroll-header-panel` bug?

Thank you in advance.

**Comment by blasten** [comment]
@MeloJR thanks this issue is confirmed.

**Comment by softkot** [comment]
IMHO there is a bug in neon-animatable that implements only Polymer.NeonAnimatableBehavior and i think it should have both Polymer.NeonAnimatableBehavior and Polymer.IronResizableBehavior

As a workaround i am using following code snipped before any other component imports

```
<link rel="import" href="../bower_components/neon-animation/neon-animatable-behavior.html">
<link rel="import" href="../bower_components/iron-resizable-behavior/iron-resizable-behavior.html">

<script>
    (function () {
        Polymer.NeonAnimatableBehavior = [Polymer.NeonAnimatableBehavior, Polymer.IronResizableBehavior];
    })();
</script>
```

**Comment by MeloJR** [comment]
The snippet you proposed solves this problem and others of the same nature. Thank you so much!

**Comment by Tanbouz** [comment]
It bugs for me if the page containing this element is lazy loaded on Chrome. Works fine on Firefox and Edge with the neon animated pages.

When it bugs, the measuredHeaderHeight is zero. Only if I use setTimeout and call measuredHeaderHeight after a little while it works and return the true header height.

**Comment by ozasadnyy** [comment]
The same for me.

It works only with a timeout. Even with 0 delay:

```
setTimeout(function(){
  document.querySelector('#scrollHeaderPanel').measureHeaderHeight();
  document.querySelector('#scrollHeaderPanel').scroller.scrollTop = 0;
}, 0);
```

**Comment by andyfinity** [comment]
This issue affected me too.

My workaround involved running .measureHeaderHeight() like others have done, and that appears to fix most of my problems. However, I have a tall header that condenses to a normal one which doesn't behave properly.

![selection_016](https://cloud.githubusercontent.com/assets/600005/10680164/0f53d2de-78d2-11e5-9b23-316bd0435af1.png)

This behavior seems to only be seen when on a particularly narrow desktop browser (tested on Chrome and Firefox). Mobile devices aren't affected, and Chrome in Device Mode didn't exhibit the behavior either.

**Comment by blasten** [comment]
This issue is now fixed in https://github.com/PolymerElements/neon-animation/releases/tag/v1.0.8
