### ISSUE TITLE
Lines 591-> 593 cause Firefox to crash

### ISSUE THREAD

**Issue by markstewie** [PolymerElements/paper-scroll-header-panel#38]
This part of the code causes Firefox to crash in the latest version

```
  if (!event || !this.fixed && y !== this._y) {
    this._transformHeader(y);
  }
```

Console logs `ReferenceError: event is not defined`

Commenting these lines out fixes the problem.

**Comment by blasten** [comment]
Thanks for reporting the issue. This has been fixed. 
You can run `bower update`
