### ISSUE TITLE
keepCondensedHeader doesn't appear to work

### ISSUE THREAD

**Issue by jordangarside** [PolymerElements/paper-scroll-header-panel#40]
I believe `keepCondensedHeader` is supposed to keep the condensed version of the header at the top of the page without hiding, but it doesn't seem to do anything when enabled (the condensed bar still hides on scroll down).

The `fixed` option doesn't work for this purpose either as it keeps the whole header height without respecting the `condenses` option.

I'm sorry I don't have time to do a demo right now.

**Comment by blasten** [comment]
Here's an example: http://jsbin.com/najuwa/edit?html,output. Attribute names use hyphens instead of camelCase.

**Comment by jordangarside** [comment]
Thank you.
