### ISSUE TITLE
paper-header not working on chrome 44

### ISSUE THREAD

**Issue by bipin-nag** [PolymerElements/paper-scroll-header-panel#42]
I am using paper-header class for my custom toolbar element. Firefox shows the content properly but chrome does not.

```
<body unresolved class="fullbleed layout vertical">
    <paper-scroll-header-panel class="flex">
      <toptoolbar-user class="paper-header">
      </toptoolbar-user>
      <paper-drawer-panel id="paperDrawerPanel" style="">
        <!-- Drawer Scroll Header Panel -->
        <paper-header-panel drawer fixed style="">
        </paper-header-panel>
       ...
      </paper-drawer-panel>
    </paper-scroll-header-panel>
</body>
```

In firefox:
![firefox](https://cloud.githubusercontent.com/assets/364851/9396006/723b5858-47af-11e5-9f3d-c6d61d37bf67.png)

In chrome:
![chrome](https://cloud.githubusercontent.com/assets/364851/9396005/7236d8c8-47af-11e5-98d7-224030e4737b.png)

**Comment by blasten** [comment]
@bipin-nag the `paper-header` class should be used inside a `paper-header-panel`. e.g. 

``` html
<paper-header-panel>
  <div class="paper-header"> Header </div>
  <div class="content"> </div>
</paper-header-panel>
```

Feel free to open an issue in https://github.com/PolymerElements/paper-header-panel if you need more help.

**Comment by bipin-nag** [comment]
@blasten But according to the [documentation](https://elements.polymer-project.org/elements/paper-scroll-header-panel) paper-header can be used for scroll-header-panel.

**Comment by blasten** [comment]
I'd say that you can still refactor your code a little bit, so you can have a toolbar for the drawer and a toolbar for the main content. e.g. http://jsbin.com/tiwuze/edit?html,output
