### ISSUE TITLE
Can't set dynamic class

### ISSUE THREAD

**Issue by ozasadnyy** [PolymerElements/paper-scroll-header-panel#43]
Hello developers.

How to set dynamic class for `paper-scroll-header-panel`?

At first I have tried this way:

```
<paper-scroll-header-panel id="scrollHeaderPanel" class="{{person.panelClass}}" condenses keep-condensed-header>
...

Polymer({
        is: 'person-dialog',
        properties: {
           person: Object
        }
});
```

But after rendering I don't get my class for the element.

Then I have tried manually add class to `paper-scroll-header-panel`, but my styles also doesn't work:

```
:root {
      --android: #78C257;
   }
paper-scroll-header-panel.android {
      --paper-scroll-header-panel-full-header: {
         background-color: var(--android);
      } ;
      --paper-scroll-header-panel-condensed-header: {
         background-color: var(--android);
      };
}
```

Any ideas how to overcome this problem?

**Comment by samccone** [comment]
hi @ozasadnyy 

You will want to use `attribute-binding`

#### `$=`

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding

``` html
<paper-scroll-header-panel id="scrollHeaderPanel" class$="{{person.panelClass}}" condenses keep-condensed-header>
```

**Comment by ozasadnyy** [comment]
@samccone Yeah, my bad, but I have a problem how to make my style works.
