### ISSUE TITLE
paper-scroll-header-panel not condensing on mobile with shadow dom polyfill

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/paper-scroll-header-panel#45]
The paper-scroll-header-panel condenses as expected on desktop but on mobile it stays in its expanded state and/or behaves buggy. It only works if I change orientation and switch back. 

I'll try to send a link where you can see it happening soon.

**Comment by blasten** [comment]
+1 please share the link

**Comment by blasten** [comment]
This issue appears to have been fixed. Please reopen if the issue is still present.
