### ISSUE TITLE
Feature request: cover mode

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-scroll-header-panel#47]
One thing that `paper-header-panel` has is `mode="cover"`, which gives you a nice card over banner UI:

<img width="1205" alt="screen shot 2015-09-11 at 7 35 45 am" src="https://cloud.githubusercontent.com/assets/238208/9817472/eb711bd2-5857-11e5-9ea6-ae8ca3cc04c0.png">

Problem is that when using this element with a negative margin on the main content, you have to set `position:relative;z-index: 1` yourself. That makes the drawer panel layering very unhappy:

<img width="1205" alt="screen shot 2015-09-11 at 7 35 50 am" src="https://cloud.githubusercontent.com/assets/238208/9817465/e7aa5072-5857-11e5-8edb-64d7829402fb.png">

Would be awesome if there were custom prop styling hooks for these bits or if this element handled that case well with a `mode="cover"` feature.

**Comment by blasten** [comment]
:+1: you should check out polymerlabs/app-layout :)

**Comment by blasten** [comment]
We support this now in app-layout: https://github.com/PolymerLabs/app-layout. Please see https://github.com/PolymerLabs/app-layout/blob/master/app-header/demo/music.html
