### ISSUE TITLE
using this element brakes css parallax effect 

### ISSUE THREAD

**Issue by elynch303** [PolymerElements/paper-scroll-header-panel#49]
when using this element images with  background-attachment: fixed; brake.

**Comment by blasten** [comment]
@elynch303 can you provide a code to see how you are using this element?

**Comment by blasten** [comment]
Please reopen when you have an example.

**Comment by elynch303** [comment]
https://github.com/elynch303/paper-scroll-header-panel/blob/parallax-brake-example/demo/brake-example.html

i forked the repo and made a example file so you can see this issue 

the working parallax sample can be found here http://codepen.io/keithclark/pen/JycFw

let me know if you need anything else i can do to help. 
I will delete the branch once you are done with it.

**Comment by elynch303** [comment]
@blasten i have added some sample code for testing in the comment above

**Comment by blasten** [comment]
@elynch303 I see.  `background-attachment: fixed;` requires document scrolling which isn't currently supported by paper-scroll-header-panel; however, you can use app-header which has a few demos using the document scroll. https://github.com/PolymerLabs/app-layout

**Comment by elynch303** [comment]
@blasten thanks man for the work around (for now i just used the paper-toolbar and added the show nav on scroll function manually with js), just wondering if there is any plans on supporting background-attachment: fixed; if i can find a solution i will submit a pull request. keep me posted.
