### ISSUE TITLE
documentation methods vs properties

### ISSUE THREAD

**Issue by JacekKosciesza** [PolymerElements/paper-scroll-header-panel#52]
There is some inconsistency in documentation e.g. scroller is a property and you use it like this paperScrollHeaderPanel.scroller but documentation says that it is a method which suggests that you use it like this paperScrollHeaderPanel.scroller()

**Comment by frankiefu** [comment]
This is an issue in the hydrolysis tool which the doc page uses to get the info.  Filed hydrolysis issue: https://github.com/Polymer/hydrolysis/issues/144
