### ISSUE TITLE
Feature request:  to be able to style component  scrollbar

### ISSUE THREAD

**Issue by albertolobrano** [PolymerElements/paper-scroll-header-panel#53]

**Comment by samccone** [comment]
@albertolobrano what does 

> customize the scrollbar

Mean to you? What would the API look like, what features are you looking for?

**Comment by albertolobrano** [comment]
Right now is not possible to style the component scrollbar because of the style encapsulation.   

How can we style the component scrollbar ?  For example how can i inject the following css into the component?  

::-webkit-scrollbar {
  -webkit-appearance: none;
}

::-webkit-scrollbar:vertical {
  width: 10px;
}

::-webkit-scrollbar:horizontal {
  height: 12px;
}

::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, .5);
  border-radius: 0px;
  border: 2px solid #ffffff;
}

::-webkit-scrollbar-track {
  border-radius: 0px;
  background-color: transparent;
}

**Comment by blasten** [comment]
so many pseudo elements.... Feel free to send a PR to include a css mixin for this feature.

**Comment by albertolobrano** [comment]
Using the scroller i am able to customize it as i like.  I will send you a pr just to include a mixing to facilitate the styling of the component.

**Comment by blasten** [comment]
closing this.

**Comment by t-mdo** [comment]
Hum. Have this feature been implemented ?
