### ISSUE TITLE
Feature request: Change the condensing ratio into a property

### ISSUE THREAD

**Issue by 43081j** [PolymerElements/paper-scroll-header-panel#59]
Currently the condensed header height is measured by 1/3 of the total height.

This works fine if using a toolbar with class `.tall` because there are 3 equal-height sections, so 1/3 results in the bottom section displaying.

However, if you use `.medium-tall` or no class at all, clearly 1/3 will cut through the middle of the toolbar. For example, a `.medium-tall` toolbar shows half of the bottom section.

Really, this 1/3 should probably be a property we can change. I don't want to set a fixed height because the height of the toolbar changes via CSS responsively (128px normally, 112px on mobile). This means that setting a condensed header height of `128px` will not work right in mobile.

This seems like a very common situation to be in, so am I possibly missing some simple solution? Surely someone else has tried a condensing header with a `.medium-tall` toolbar.

**Comment by blasten** [comment]
@43081j Have you consider using the `header-height` and `condensed-header-height` properties?

**Comment by 43081j** [comment]
This isn't really a closed issue. As specified in my original comment:

> I don't want to set a fixed height because the height of the toolbar changes via CSS responsively (128px normally, 112px on mobile)

The `1/3` value is essentially a magic number and belongs in a variable. 

By setting a specific header height, you are assuming the header is always the same height. In many cases, it is not, rather it is responsive and reduces in size on lower resolutions. This would be easy to deal with if the `1/3` value could be set to something else (in this case, `1` would do fine to show the whole header).

In fact, 1/3 _only_ works on `tall` headers, so out of the box this is broken for the other two header sizes.
