### ISSUE TITLE
bg9.jpg - copyright violation

### ISSUE THREAD

**Issue by vlna** [PolymerElements/paper-scroll-header-panel#63]
## Status

`/demo/images/bg9.jpg` looks like a screenshot from a copyrighted film **Moonrise Kingdom**, and the 
copyright for it is most likely owned by the studio **Universal Pictures** which produced the film.

See https://www.youtube.com/watch?v=_eOI3AamSm8&feature=youtu.be&t=1m49s
## Expected change

I guess this image is used without copyright holder approval and should be removed or replaced with Public Domain/CC0 one.

**Comment by blasten** [comment]
Hi @vlna. Thanks for the report. The image has been removed.

**Comment by vlna** [comment]
Hi @blasten. I checked images you used as replacement. Are you sure they are PD/CC0? It looks for me like leaked backgrounds from LG G Watch - http://www.androidpolice.com/2014/06/03/leak-alleged-system-dump-from-lg-g-watch-emerges-video-of-bootloader-animation-shows-up-on-youtube/

At least `bg1.jpg` is for sale on http://www.dreamstime.com/stock-image-purple-ranges-horizontal-image1098981 and `bg2.jpg` on http://www.istockphoto.com/photo/hill-ridges-in-mist-showing-atmospheric-perspective-at-sunset-19720756

Some `README` within images directory will help users ~~identify~~ confirm origin and license of images.

**Comment by frankiefu** [comment]
@vlna  Yeah we have the license. Polymer is a Google project.
