### ISSUE TITLE
Font size too big for the container

### ISSUE THREAD

**Issue by yask123** [PolymerElements/paper-scroll-header-panel#66]
This bug exists for `Transform header 3` and `Transform header 4` example.
[Link](https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-3.html&active=paper-scroll-header-panel) 
Font size too big for the container `bottomBar`
![ohix3vdokelrkgukvno37l7mhtjh8hbca_h7-us2p1s](https://cloud.githubusercontent.com/assets/1812021/11143030/f7d363f2-8a17-11e5-8ff8-5aa5e8e572db.png)

![juqc9hkxpy1lvw7qxc1iph6zdudseofhau_-tzetzrm](https://cloud.githubusercontent.com/assets/1812021/11143058/4a981628-8a18-11e5-9b3e-6e09e09b5f66.png)

**Comment by blasten** [comment]
The issue is that paper-toolbar sets `overflow: hidden` to the title. https://github.com/PolymerElements/paper-toolbar/blob/master/paper-toolbar.html#L193
