### ISSUE TITLE
Uncaught TypeError: Illegal invocation (Transform related?)

### ISSUE THREAD

**Issue by Alos** [PolymerElements/paper-scroll-header-panel#70]
The `paper-scroll-header-panel` with a `paper-toolbar` element causes Chrome and Safari to fill the console with errors. The application works as expected and the toolbar is able to resize correctly. 
## Expected outcome

No errors should be triggered by scrolling.
## Actual outcome

The console will get a few errors every time the toolbar must change its hight. This happens in Chrome, Safari. Firefox outputs a different error. 
## Steps to reproduce

Not sure if I should file this here or on Polymer (or if I'm using Polymer wrong), I have a PolymerStarterKit app running where I have the following structure:

``` html
 <paper-drawer-panel id="paperDrawerPanel">

     <paper-scroll-header-panel drawer fixed>
      <!-- Some nice stuff here -->
     </paper-scroll-header-panel>
      <div main>
        <iron-pages attr-for-selected="data-route" selected="{{route}}">
          <section data-route="meh">
             <my-element></my-element>
          </section>
        </iron-pages>
      </div>
</paper-drawer-panel>
```

Then in "my-element" in its template I have a paper-scroll-header-panel with a toolbar:

``` html
<paper-scroll-header-panel id="worksScroller" condenses keep-condensed-header>
    <paper-toolbar id="theToolbar">
        <div class="middle title">A title</div>
        <div class="flex"></div>
         <paper-fab icon="create"></paper-fab>
    </paper-toolbar>
    <div>
        <iron-list items="{{items}}" as="item">
            <template>
                <div class="container">
                    <paper-material elevation="1">
                           <!-- My model details here -->
                    </paper-material>
                </div>
            </template>
        </iron-list>
    </div>
</paper-scroll-header-panel>
```

The app works correctly, there are some errors when I start scrolling and the toolbar needs to shrink:

Chrome and Safari:

> Uncaught TypeError: Illegal invocationPolymer.Base._addFeature.transform @ polymer.html:1332(anonymous function) @ app.js:52Polymer.Base._addFeature.fire @ polymer.html:1306Polymer.PaperScrollHeaderPanel.Polymer._transformHeader @ paper-scroll-header-panel.html:496Polymer.PaperScrollHeaderPanel.Polymer._updateScrollState @ paper-scroll-header-panel.html:568Polymer.PaperScrollHeaderPanel.Polymer._scroll @ paper-scroll-header-panel.html:536
> polymer.html:1332 Uncaught TypeError: Illegal invocationPolymer.Base._addFeature.transform @ polymer.html:1332(anonymous function) @ app.js:52Polymer.Base._addFeature.fire @ polymer.html:1306Polymer.PaperScrollHeaderPanel.Polymer._transformHeader @ paper-scroll-header-panel.html:496Polymer.PaperScrollHeaderPanel.Polymer._setup @ paper-scroll-header-panel.html:476Polymer.Base.extend._complexObserverEffect @ polymer.html:1567(anonymous function) @ polymer.html:1411Polymer.Bind._modelApi._effectEffects @ polymer.html:1408Polymer.Bind._modelApi._propertySetter @ polymer.html:1393setter @ polymer.html:1469Polymer.PaperScrollHeaderPanel.Polymer.measureHeaderHeight @ paper-scroll-header-panel.html:364handler @ polymer.html:471Polymer.Base._addFeature.fire @ polymer.html:1306Polymer.IronResizableBehavior._fireResize @ iron-resizable-behavior.html:149Polymer.IronResizableBehavior.notifyResize @ iron-resizable-behavior.html:99Polymer.IronResizableBehavior._notifyDescendant @ iron-resizable-behavior.html:188(anonymous function) @ iron-resizable-behavior.html:95Polymer.IronResizableBehavior.notifyResize @ iron-resizable-behavior.html:93

Firefox has another opinion:

> TypeError: 'style' getter called on an object that does not implement interface HTMLElement.

Chrome tags the error in this section:

``` javascript
transform: function (transform, node) {
node = node || this;
node.style.webkitTransform = transform; //<----here
node.style.transform = transform;
}
```

Have I made a mistake? :S

**Comment by blasten** [comment]
@Alos Thanks for the well documented issue.  Which version of Polymer and paper-scroll-header-panel are you using?

**Comment by Alos** [comment]
@blasten Hi there, the versions that come with the [Polymer Starter Kit 1.1.1](https://github.com/polymerelements/polymer-starter-kit/releases):

Polymer 1.2.1
paper-scroll-header-panel 1.0.9

**Comment by cgriffin4** [comment]
I'm not sure what changed but @Alos check and see if your middleContainer and bottomContainer are 'undefined'. I am running an app similar to the Starter Kit and had the same error that I resolved by changing var middleContainer = Polymer.Base.Dom(document)... to var middleContainer = app... (the code in the paper-header-transform listener is in app.js.)

**Comment by Alos** [comment]
@cgriffin4 you are totally right! I removed those lines and the application worked perfectly! My bad!
