### ISSUE TITLE
paper-drawer-toggle not working with it

### ISSUE THREAD

**Issue by hedcet** [PolymerElements/paper-scroll-header-panel#78]
I want to toggle `paper-drawer-panel` drawer from `paper-scroll-header-panel > paper-toolbar > icon="menu"`, the code below

```
<paper-drawer-panel>
<paper-header-panel drawer></paper-header-panel>
<neon-animated-pages class="fit" main selected="0">
<neon-animatable>
<paper-scroll-header-panel condenses>
<paper-toolbar id="main_toolbar">
    <paper-icon-button class="selection-hidden" icon="menu" paper-drawer-toggle></paper-icon-button>

    <div class="title" id="main_toolbar_title">patentability</div>
</paper-toolbar>

<div class="content"></div>
</paper-scroll-header-panel>
</neon-animatable>
</neon-animated-pages>
</paper-drawer-panel>
```

not working with `paper-scroll-header-panel`

How i toggle `paper-drawer-pane`l drawer from `paper-scroll-header-panel > paper-toolbar > icon="menu"` ?

[github](https://github.com/HedCET/patentability_polymer/blob/master/.polymer/linto/layout-inbox.html#L180)

[stackoverflow](http://stackoverflow.com/questions/34383720/paper-drawer-toggle-not-working-with-paper-scroll-header-panel)

**Comment by ebidel** [comment]
Please post a jsbin of the issue.
