### ISSUE TITLE
not working if multiple paper-scroll-header-panel inside neon-animated-page

### ISSUE THREAD

**Issue by hedcet** [PolymerElements/paper-scroll-header-panel#79]
http://jsbin.com/winedi/edit?html,output

after switching neon-animated-page from 0'th page to 1'st page (both contains independent paper-scroll-header-panel) paper-scroll-panel in the 1'st page not working

**Comment by blasten** [comment]
@HedCET is this the right jsbin? I didn't see the paper-scroll-header-panel/neon-animated-page...

**Comment by hedcet** [comment]
@blasten actually i got answer here http://stackoverflow.com/questions/34405453/paper-scroll-header-panel-not-working
