### ISSUE TITLE
Condensed Header not visible on scroll down

### ISSUE THREAD

**Issue by tmess567** [PolymerElements/paper-scroll-header-panel#8]
I've set the keepCondensedHeader property to true and yet the condensed header is not visible on scroll down. It is however visible on scroll up.

I'm sure this is a trivial issue but I've been stuck at this for the past day and can't seem to solve it..
Here's my code: http://pastebin.com/aDiFmgEz

**Comment by ebidel** [comment]
Have you tried `keep-condensed-header` for the attribute? Camel-cased properties are need to be written with "-". https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping
