### ISSUE TITLE
Loading the element async produces undefined errors

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/paper-scroll-header-panel#80]
I'm not sure the root cause of this issue but here's what I've been able to dig up.

When I load the element async and it has a condenses attribute, the `condensesChanged` observer runs immediately, causing `_updateScrollState` to run. In this function, the `ctx` object is undefined, so checks [like this](https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L560) fail and cause an error. It seems like the `Polymer.PaperScrollHeaderPanel` property has not had a chance to be created when that observer fires. Using `this.async` inside of `_updateScrollState` seems to fix the issue.

**Comment by blasten** [comment]
@robdodson We could also add a `isAttached` parameter to each of the observers. Could you try replacing the observers in https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L287-L292  for:

``` js
      '_setup(headerHeight, condensedHeaderHeight, fixed, isAttached)',
      '_condensedHeaderHeightChanged(condensedHeaderHeight, isAttached)',
      '_headerHeightChanged(headerHeight, condensedHeaderHeight, isAttached)',
      '_condensesChanged(condenses, isAttached)',
    ],
```

In that way, the observers will only run after attaching the scroll-header-panel. I hope that fixes the issue.

**Comment by robdodson** [comment]
Hm it's working a little better but still broken. Now I'm getting different errors :)

<img width="1022" alt="screen shot 2015-12-22 at 9 05 36 am" src="https://cloud.githubusercontent.com/assets/1066253/11961079/33f2b91e-a88b-11e5-951f-730e1eb02015.png">

**Comment by blasten** [comment]
hmmm. I see. Is the scroll-header-panel already attached before upgrading it?

**Comment by robdodson** [comment]
hm weird. So the elements are just sitting on the page in html. Putting console logs in `attached` shows that the attached handler never runs.

```
ready: function() {
      console.log('ready');
      this._scrollHandler = this._scroll.bind(this);
      this.scroller.addEventListener('scroll', this._scrollHandler);
    },

    attached: function() {
      console.log('attached');
      this.async(this.measureHeaderHeight, 1);
    },
```

I do see the console log from ready though

**Comment by blasten** [comment]
That's weird. The element is on the page, and then you upgrade async? Can you reproduce it in jsbin?

**Comment by robdodson** [comment]
For anyone following along at home... Sent over a sample but the team is on holiday so we'll resume when folks roll back in :christmas_tree: :santa:

**Comment by blasten** [comment]
@robdodson would have a jsbin to repro the issue/ steps to repro the issue?

**Comment by jasmith79** [comment]
Same issue. 
Steps to repro
In a script inside the head tag
Create a link tag with the appropriate href and rel attributes
Append to document head
In the body is an auto-binding template containing a `paper-scroll-header-panel`.
Errors ensue.

Downloading the latest (1.2.1) Polymer Starter Kit and replacing the 

`<link rel="import" href="elements/elements.html">`

line with 

``` html
  <script>
    var importURLs = ['elements/elements.html'];
    if (importURLs.length) {
      window.addEventListener('DOMContentLoaded', function() {
        var url;
        window.Polymer = window.Polymer || {};
        window.Polymer.dom = 'shadow';
        while (url = importURLs.shift()) {
          var elem = document.createElement('link');
          elem.rel = 'import';
          elem.href = url;
          document.head.appendChild(elem);
        }
      });
    }
  </script>
```

will show the error. The `paper-header-transform` event listener in the starter kit is not necessary to reproduce the error.

**Comment by robdodson** [comment]
I can also try to put together a jsbin later today if that helps :)

**Comment by robdodson** [comment]
Sent you a zip which demonstrates the issue

**Comment by vguillou** [comment]
Another way to reproduce the problem :
- `git clone` <a href="https://github.com/PolymerElements/polymer-starter-kit">Polymer Starter Kit</a> 
- <a href="https://github.com/PolymerElements/polymer-starter-kit#install-dependencies">Install the dependencies</a>
- Follow the <a href="https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/polymer-perf.md">Polymer Performance Recipe</a>
- Run `gulp serve` and open <a href="http://localhost:5000/">http://localhost:5000/</a> in Chrome.

<b>Edit :</b> Oups sorry, I didn't see <a href="https://github.com/PolymerElements/polymer-starter-kit/issues/503">this reference</a> :+1:

**Comment by blasten** [comment]
Repro case: http://jsbin.com/tozuwu/edit?html,output. This seems like a Polymer bug. There are a few more elements that might have the same issue:
1. https://github.com/PolymerElements/paper-menu-button/blob/master/paper-menu-button.html#L372-L373
2. https://github.com/PolymerElements/iron-menu-behavior/blob/master/iron-menu-behavior.html#L310
