### ISSUE TITLE
Error changing the fixed attribute dynamically

### ISSUE THREAD

**Issue by horochovec** [PolymerElements/paper-scroll-header-panel#81]
Hello,

I trying to change my toolbar dynamically, removing the attribute "fixed" on my "paper-scroll-header-panel" and adding the class "medium-tall" on my "paper-toolbar":

this.$.headerPanel.removeAttribute("fixed");
this.$.toolbar.classList.add("medium-tall");

and using this to update my styles:
this.$.headerPanel.updateStyles();
this.$.toolbar.updateStyles();
or
Polymer.updateStyles();

but this change only works well when there is a scroll bar on the content, otherwise my toolbar is extremely small, making not assert application of "medium-tall".

Any idea how I can fix this?

**Comment by blasten** [comment]
You may need to call `this.$.headerPanel.measureHeaderHeight()` after. Please reopen if the issue is still present.
