### ISSUE TITLE
/deep/ combinator is deprecated

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-scroll-header-panel#82]
From Chrome Console Version 47.0.2526.106 (64-bit)

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-1.html&active=paper-scroll-header-panel

**Comment by blasten** [comment]
hmm. those /deep/ are coming from here `view-source:https://elements.polymer-project.org/elements/elements.build.html` I moved this issue to https://github.com/Polymer/polymer-element-catalog/issues/234
