### ISSUE TITLE
Custom Element that uses paper-dialog inside paper-toolbar doesn't work

### ISSUE THREAD

**Issue by LoveAndHappiness** [PolymerElements/paper-scroll-header-panel#85]
Hi,

Here is the reproduction: http://plnkr.co/edit/t8PalnvvSP6uSNuK1WPZ

When you click on **LOGIN** a dialog will appear. But the only thing that happens is that the dialog is under the <iron-overlay-backdrop>

This seems to be happening only in combination with the paper-scroll-header-panel when the `custom-element` is put in the `paper-toolbar`.

I reproduced this by not using a custom element. If I put the content of the custom element inside the 

```
    <div class="content">
                <paper-dialog id="animated">
                           <h2>Login</h2>
                </paper-dialog>
    </div>
```

How can I use custom elements inside the paper toolbar inside the paper-scroll-header-panel?

I am using the polymer-starter-kit and I'd like to use it there. Also by using just the paper-toolbar the problem does not occur.

**Comment by blasten** [comment]
Please take a look at https://github.com/PolymerElements/paper-dialog-behavior/pull/56  cc @valdrinkoshi
