### ISSUE TITLE
/deep/ combinator is deprecated.

### ISSUE THREAD

**Issue by hwebb** [PolymerElements/paper-scroll-header-panel#88]
In the console it gives the warning:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
paper-scroll-header-panel.html:357

It's not that it is breaking anything, but it's a bit annoying to have that warning all the time.
Is there a plan to fix it?

**Comment by frankiefu** [comment]
We have already taken out all the references to `/deep/` in `paper-scroll-header-panel`.  Please update to the latest version of `paper-scroll-header-panel` to see if the problem is still there.

**Comment by hwebb** [comment]
I do have the most recent version but it still complains.
It points at the line 357 and underlines ".offsetHeight" on the code:
if (header && header.offsetHeight) {

Thanks.

**Comment by blasten** [comment]
@hwebb It might be coming from some place else. Feel free to reopen the issue if you found where it was coming from.  You could add a `console.warn` to iron-shadow-flex-layout.html

**Comment by hwebb** [comment]
Thanks for the reply. Indeed I was calling iron-flex-layout/classes/iron-flex-layout.html, I've changed it to iron-flex-layout/iron-flex-layout-classes.html and it works.
