### ISSUE TITLE
Documentation on insertion points is outdated

### ISSUE THREAD

**Issue by sevcsik** [PolymerElements/paper-scroll-header-panel#9]
The documentation in the Catalog (https://elements.polymer-project.org/elements/paper-scroll-header-panel) says:

> paper-scroll-header-panel works well with paper-toolbar but can use any element that represents a header by adding a core-header class to it.

Which is outdated, since the correct class name is `paper-header` not `core-header`. See the insertion point in the template:

``` html
<content id="headerContent" select="paper-toolbar, .paper-header"></content>
```

https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L147

**Comment by blasten** [comment]
fixed now.

**Comment by blasten** [comment]
Actually, this element was renamed to `paper-header-panel`

**Comment by blasten** [comment]
fixed now!
