### ISSUE TITLE
swiping up on Android Chrome does not hide browser tabs and address bar

### ISSUE THREAD

**Issue by alfalabs** [PolymerElements/paper-scroll-header-panel#98]
### Description

When using  `paper-header-panel` or`paper-scroll-header-panel` swiping up does not hide browser UI - browser tabs and browser address bar remain visible taking up space. This reduces web page viewing area.
### Expected outcome

Web page should be viewable "full screen" when user swipes up. Here is the example:
http://www.alfamodellini.com.s3-website-eu-west-1.amazonaws.com/index-noPHP.html
### Actual outcome

Browser UI stays in view when swiping up
Example with `paper-scroll-header-panel`:
http://www.alfamodellini.com.s3-website-eu-west-1.amazonaws.com/
Example with `paper-header-panel`:
http://www.alfamodellini.com.s3-website-eu-west-1.amazonaws.com/index-PHP.html
### Live Demo

see above examples
### Steps to reproduce

put  `paper-header-panel` or`paper-scroll-header-panel` on a page and view it on Android device using Chrome or Firefox browser.

### Browsers Affected

- [X] Chrome on Android
- [X] Firefox on Android

Devices Nexus 7 with Android 4.4.4, Nexus 5 with Android 4.4.4
other not tested

Also filed in https://github.com/PolymerElements/paper-header-panel/issues/84

**Comment by alfalabs** [comment]
A week passed, I had to remove Live Demo examples from server. Hopefully the explanation is enough to understand the issue.

**Comment by blasten** [comment]
This issue is fixed in app-layout https://github.com/PolymerElements/app-layout
